export {Home} from './Home'
export {ChannelList} from './ChannelList'
export {ContactUs} from './ContactUs'
export {Pricing} from './Pricing'
export {FAQ} from './FAQ'
export {Tutorial} from './Tutorial'
export {Reseller} from './Reseller'