export const channelsList = [
  {
    heading: 'VIP channels',
    channels: [
      "DAZN 1 Bar FHD DE VIP",
      "DAZN 2 Bar FHD DE VIP",
      "DAZN Bar 1 HD DE VIP",
      "DAZN Bar 2 HD DE VIP",
      "Planet Spons 1 FHD HR VIP",
      "Planet Spons 2 FHD HR VIP",
      "Planet Spons 3 FHD HR VIP",
      "Planet Spons 4 HD HR VIP",
      "Planet Spons 5 HD HR VIP",
      "Eleven Sports 1 FHD PT",
      "Eleven Sports 2 FHD PT",
      "Eleven Sports 3 FHD PT",
      "Eleven Sports 4 FHD PT",
      "Eleven Sports 5 FHD PT",
      "Eleven Sports 6 FHD PT",
      "MySports FHD CH",
      "MySports 1/Sky 1 FHD CH",
      "MySports 2/Sky 2 FHD CH",
      "MySports 3/Sky 3 FHD CH",
      "MySports 4/Sky 4 FHD CH",
      "MySports 5/Sky 5 FHD CH",
      "MySports 6/Sky 6 FHD CH",
      "MySports 7/Sky 7 FHD CH",
      "MySports 8/Sky 8 FHD CH",
      "MySports 9/Sky 9 FHD CH",
      "Eleven Sports 1 FHD BE",
      "Eleven Sports 2 FHD BE",
      "Eleven Sports 1 FHD PL",
      "Eleven Sports 2 FHD PL",
      "beIN Sports 1 FHD ARB",
      "beIN Sports 2 FHD ARB",
      "beIN Sports 3 FHD ARB",
      "beIN Sports 4 FHD ARB",
      "beIN Sports 5 FHD ARB",
      "beIN Sports 6 FHD ARB",
      "beIN Sports 7 FHD ARB",
      "beIN Sports 8 FHD ARB",
      "beIN Sports 9 FHD ARB",
      "beIN Sports 10 FHD ARB",
      "beIN Sports News FHD ARB",
      "beIN Sports 1 FHD TR",
      "beIN Sports 2 FHD TR",
      "beIN Sports 3 FHD TR",
      "beIN Sports 4 FHD TR",
      "Animal Planet FHD EN",
      "MBC Variety HD ARB",
      "Rotana Aflam HD ARB",
      "beIN Sports Max 1 FHD VIP FR",
      "beIN Sports MAX 5 FHD FR",
      "beIN Sports MAX 6 FHD FR",
      "beIN Sports MAX 7 FHD FR",
      "beIN Sports MAX 8 FHD FR",
      "beIN Sports MAX 9 FHD FR",
      "beIN Sports MAX 10 FHD FR",
      "ATG Live SE",
      "C More Junior VIP FI",
      "C More Juniori VIP FI",
      "C More Spon 1 VIP FI",
      "C More Spon 1 FHD VIP FI",
      "C More Spon 2 VIP FI",
      "C More Spon HD VIP FI",
      "C More Max HD VIP FI",
      "Jim TV VIP FI",
      "MTV 3 FHD VIP FI",
      "Nat Geo Wild HD VIP SC",
      "Nelonen VIP FI",
      "Sub TV VIP FI",
      "Viasat 4 VIP SC",
      "Viasat Explore VIP SC",
      "Viasat Fotboll HD VIP SC",
      "Viasat Golf HD VIP SC",
      "Viasat Nature VIP NO",
      "Viasat Series VIP NO",
      "Yle TV 1 FHD VIP FI",
      "Cooking Channel HD US VIP",
      "FOX Business HD US VIP",
      "Fox Sports Arizona HD US VIP",
      "Fox Sports College Pacific HD US VIP",
      "Fox Sports Florida HD US VIP",
      "Fox Sports North HD US VIP",
      "Fox Sports Ohio HD US VIP",
      "Fox Sports San Diego HD US VIP",
      "Fox Sports South HD US VIP",
      "Fox Sports South East HD US VIP",
      "Fox Sports South West HD US VIP",
      "Fox Sports Sun HD US VIP",
      "Fox Sports West HD US VIP",
      "Fox Sports Wisconsin HD US VIP",
      "The Weather Channel HD US VIP",
      "Univision HD US VIP",
      "Beout Spons 1 HD AR",
      "NFL SUNDAY TICKET 705 US",
      "WGN America HD US",
      "WWE NETWORK HD US",
      "Yes Network FHD US",
      "Fury vs Wilder 2 PPV FHD VIP",
      "Telekom Eishockey 1 FHD DE Live During Events Only]",
      "Telekom Eishockey 2 FHD DE Live During Events Only]",
      "Telekom Eishockey 3 FHD DE Live During Events Only]",
      "Telekom Eishockey 4 FHD DE Live During Events Only]",
      "Telekom Eishockey 5 FHD DE Live During Events Only]",
      "Telekom Eishockey 6 FHD DE Live During Events Only]",
      "Telekom Eishockey 7 FHD DE Live During Events Only]",
    ]
  }
]