export const channelsList = [
  {
    name: 'USA VIP channels',
    channels: [
      "DAZN 1 Bar FHD DE VIP",
      "DAZN 2 Bar FHD DE VIP",
      "DAZN Bar 1 HD DE VIP",
      "DAZN Bar 2 HD DE VIP",
      "Planet Spons 1 FHD HR VIP",
      "Planet Spons 2 FHD HR VIP",
      "Planet Spons 3 FHD HR VIP",
      "Planet Spons 4 HD HR VIP",
      "Planet Spons 5 HD HR VIP",
      "Eleven Sports 1 FHD PT",
      "Eleven Sports 2 FHD PT",
      "Eleven Sports 3 FHD PT",
      "Eleven Sports 4 FHD PT",
      "Eleven Sports 5 FHD PT",
      "Eleven Sports 6 FHD PT",
      "MySports FHD CH",
      "MySports 1/Sky 1 FHD CH",
      "MySports 2/Sky 2 FHD CH",
      "MySports 3/Sky 3 FHD CH",
      "MySports 4/Sky 4 FHD CH",
      "MySports 5/Sky 5 FHD CH",
      "MySports 6/Sky 6 FHD CH",
      "MySports 7/Sky 7 FHD CH",
      "MySports 8/Sky 8 FHD CH",
      "MySports 9/Sky 9 FHD CH",
      "Eleven Sports 1 FHD BE",
      "Eleven Sports 2 FHD BE",
      "Eleven Sports 1 FHD PL",
      "Eleven Sports 2 FHD PL",
      "beIN Sports 1 FHD ARB",
      "beIN Sports 2 FHD ARB",
      "beIN Sports 3 FHD ARB",
      "beIN Sports 4 FHD ARB",
      "beIN Sports 5 FHD ARB",
      "beIN Sports 6 FHD ARB",
      "beIN Sports 7 FHD ARB",
      "beIN Sports 8 FHD ARB",
      "beIN Sports 9 FHD ARB",
      "beIN Sports 10 FHD ARB",
      "beIN Sports News FHD ARB",
      "beIN Sports 1 FHD TR",
      "beIN Sports 2 FHD TR",
      "beIN Sports 3 FHD TR",
      "beIN Sports 4 FHD TR",
      "Animal Planet FHD EN",
      "MBC Variety HD ARB",
      "Rotana Aflam HD ARB",
      "beIN Sports Max 1 FHD VIP FR",
      "beIN Sports MAX 5 FHD FR",
      "beIN Sports MAX 6 FHD FR",
      "beIN Sports MAX 7 FHD FR",
      "beIN Sports MAX 8 FHD FR",
      "beIN Sports MAX 9 FHD FR",
      "beIN Sports MAX 10 FHD FR",
      "ATG Live SE",
      "C More Junior VIP FI",
      "C More Juniori VIP FI",
      "C More Spon 1 VIP FI",
      "C More Spon 1 FHD VIP FI",
      "C More Spon 2 VIP FI",
      "C More Spon HD VIP FI",
      "C More Max HD VIP FI",
      "Jim TV VIP FI",
      "MTV 3 FHD VIP FI",
      "Nat Geo Wild HD VIP SC",
      "Nelonen VIP FI",
      "Sub TV VIP FI",
      "Viasat 4 VIP SC",
      "Viasat Explore VIP SC",
      "Viasat Fotboll HD VIP SC",
      "Viasat Golf HD VIP SC",
      "Viasat Nature VIP NO",
      "Viasat Series VIP NO",
      "Yle TV 1 FHD VIP FI",
      "Cooking Channel HD US VIP",
      "FOX Business HD US VIP",
      "Fox Sports Arizona HD US VIP",
      "Fox Sports College Pacific HD US VIP",
      "Fox Sports Florida HD US VIP",
      "Fox Sports North HD US VIP",
      "Fox Sports Ohio HD US VIP",
      "Fox Sports San Diego HD US VIP",
      "Fox Sports South HD US VIP",
      "Fox Sports South East HD US VIP",
      "Fox Sports South West HD US VIP",
      "Fox Sports Sun HD US VIP",
      "Fox Sports West HD US VIP",
      "Fox Sports Wisconsin HD US VIP",
      "The Weather Channel HD US VIP",
      "Univision HD US VIP",
      "Beout Spons 1 HD AR",
      "NFL SUNDAY TICKET 705 US",
      "WGN America HD US",
      "WWE NETWORK HD US",
      "Yes Network FHD US",
      "Fury vs Wilder 2 PPV FHD VIP",
      "Telekom Eishockey 1 FHD DE Live During Events Only]",
      "Telekom Eishockey 2 FHD DE Live During Events Only]",
      "Telekom Eishockey 3 FHD DE Live During Events Only]",
      "Telekom Eishockey 4 FHD DE Live During Events Only]",
      "Telekom Eishockey 5 FHD DE Live During Events Only]",
      "Telekom Eishockey 6 FHD DE Live During Events Only]",
      "Telekom Eishockey 7 FHD DE Live During Events Only]",
    ]
  },
  {
    name: 'UK Live Sports Events',
    channels: [
      "EPL Live 1 [Match Time] HD UK",
      "EPL Live 2 [Match Time] HD UK",
      "EPL Live 3  [Match Time] HD UK",
      "EPL Live 4  [Match Time] HD UK",
      "EPL Live 5 [Match Time] HD UK",
      "EPL Live 6 [Match Time] HD UK",
      "EPL Live 7 [Match Time] HD UK",
      "EPL Live 8 [Match Time] HD UK",
      "EPL Live 9 [Match Time] HD UK",
      "EPL Live 10 [Match Time] HD UK",
      "EPL Live 11 [Match Time] HD UK",
      "EPL Live 12 [Match Time] HD UK",
      "EPL Live 13 [Match Time] HD UK",
      "EPL Live 14 [Match Time] HD UK",
      "EPL Live 15 [Match Time] HD UK",
      "EPL Live 16 [Match Time] HD UK",
      "EPL Live 17 [Match Time] HD UK",
      "EPL Live 18 [Match Time] HD UK",
      "EPL Live 19 [Match Time] HD UK",
      "EPL Live 20 [Match Time] HD UK",
      "EPL Live 21 [Match Time] HD UK",
      "EFL Live 1 [Match Time] HD UK",
      "EFL Live 2 [Match Time] HD UK",
      "EFL Live 3 [Match Time] HD UK",
      "EFL Live 4 [Match Time] HD UK",
      "EFL Live S [Match Time] HD UK",
      "EFL Live 6 [Match Time] HD UK",
      "EFL Live 7 [Match Time] HD UK",
      "EFL Live 8 [Match Time] HD UK",
      "EFL Live 9 [Match Time] HD UK",
      "EFL Live 10 [Match Time] HD UK",
      "EFL Live 11 [Match Time] HD UK",
      "EFL Live 12 [Match Time] HD UK",
      "EFL Live 13 [Match Time] HD UK",
      "EFL Live 14 [Match Time] HD UK",
      "EFL Live 15 [Match Time] HD UK",
      "EFL Live 16 [Match Time] HD UK",
      "EFL Live 17 [Match Time] HD UK",
      "EFL Live 18 [Match Time] HD UK",
      "EFL Live 19 [Match Time] HD UK",
      "EFL Live 20 [ Match Time] HD UK,",
      "EFL Live 21 [Match Time] HD UK",
      "EFL Live 22 [Match Time] HD UK",
      "EFL Live 23  [Match Time] HD UK",
      "EFL Live 24  [Match Time] HD UK",
      "EFL Live 25 [Match Time] HD UK",
      "EFL Live 26  [Match Time] HD UK",
      "EFL Live 27  [Match Time] HD UK",
      "EFL Live 28 [Match Time] HD UK",
      "EFL Live 29 [Match Time] HD UK",
      "EFL Live 30  [Match Time] HD UK",
      "EFL Live 31  [Match Time] HD[ UK",
      "EFL Live 32 [Match Time] HD UK",
    ]
  }, {
    name: 'United States local channels',
    channels: [
      "FOX5 [New York] HD VIP US",
      "FOX43 [York] HD VIP US",
      "FOX5 Washington] HD VIP US",
      "FOX11 [Los Angeles] HD VIP US",
      "CBS9 [Los Angeles] HD VIP US",
      "CBS4 [West Palm Beach] HD VIP US",
      "NBC4 Los Angeles] HD VIP US",
      "NBC5 Chicago] HD VIP US",
      "FOX25 [Boston] HD VIP US",
      "CBS3 [Philadelphia] HD VIP US",
      "CBS21 [Detroit] HD VIP US",
      "CBS46 [Atlanta] HD VIP US",
      "FOX5 [Atlanta] HD VIP US",
      "CBS11 [Colorado Springs] HD VIP US",
      "FOX46 [Charlotte] HD VIP US",
      "NBC11 [Baltimore] HD VIP US",
      "FOX35 [Orlando] HD VIP US",
      "CBS6 [Orlando] HD VIP US",
      "FOX9 [Minneapolis] HD VIP US",
      "CBS3 [Omaha] HD VIP US",
      "NBC6 Omaha] HD VIP US",
      "FOX54 [Columbus] HD VIP US",
      "NBC38 [Columbus] HD VIP US",
      "CBS22 [South Bend] HD VIP US",
      "FOX11 [San Luis Obispo] HD VIP US",
      "CBS13 [Baltimore] HD VIP US",
      "NBC11 [Fairbanks] HD VIP US",
      "NBC5 Juneau-douglas] HD VIP US",
      "CBS4 |Texas] HD VIP US",
      "NBC21 |Texas] HD VIP US",
      "CBS4 [St. Louis] HD VIP US",
      "FOX54 [Huntsville] HD VIP US",
      "CBS4 [Kansas City] HD VIP US",
      "NBC15 [Mobile] HD VIP US",
      "NBC12 [Montgomery] HD VIP US",
      "FOX16 [Little Rock] HD VIP US",
      "NBC12 [Mesa] HD VIP US",
      "CBS5 [Phoenix] HD VIP US",
      "FOX10 [Phoenix] HD VIP US",
      "FOX11 |Tucson] HD VIP US",
      "CBS29 [Bakersfield] HD VIP US",
      "CBS11 [Savannah] HD VIP US",
      "NBC17 [Bakersfield] HD VIP US",
      "NBC24 [Chico] HD VIP US",
      "NBC24 [Fresno] HD VIP US",
      "CBS46 [Monterey] HD VIP US",
      "FOX2 [Oakland] HD VIP US",
      "FOX40 [Sacramento] HD VIP US",
      "NBC3 Sacramento] HD VIP US",
      "NBC8 Salinas] HD VIP US",
      "FOX5 [San Diego] HD VIP US",
      "CBS4 [Portland] HD VIP US",
      "FOX51 [Ocala] HD VIP US",
      "NBC7 Panama City] HD VIP US",
      "NBC40 |TaIIahassee] HD VIP US",
      "FOX13 |Tampa] HD VIP US",
      "NBC8 Tampa] HD VIP US",
      "FOX29 [West Palm Beach] HD VIP US",
      "NBC5 West Palm Beach] HD VIP US",
      "CBS12 [Augusta] HD VIP US",
      "FOX4 [Augusta] HD VIP US",
      "NBC41 [Macon] HD VIP US",
      "CB6​homasville] HD VIP US",
      "CBS5 [Honolulu] HD VIP US",
      "NBC35 [Honolulu] HD VIP US",
      "NBC6 Kurtistown] HD VIP US",
      "CBS2 [Cedar Rapids] HD VIP US",
      "NBC4 Sioux City] HD VIP US",
      "NBC13 [Des Moines] HD VIP US",
      "CBS2 [Boise] HD VIP US",
      "NBC34 [Binghamton] HD VIP US",
      "NBC2 Buffalo] HD VIP US",
      "NBC11 [Pittsburgh] HD VIP US",
      "FOX43 |Virginia Beach] HD VIP US",
      "CBS3 [Madison] HD VIP US",
      "CBS19 [Nacogdoches] HD VIP US",
      "FOX30 [San Antonio] HD VIP US",
      "NBC4 San Antonio] HD VIP US",
      "NBC6 temple] HD VIP US",
      "CBS10 Waco] HD VIP US",
      "FOX44 [Waco] HD VIP US",
      "FOX13 [Salt Lake City] HD VIP US",
      "My33 Miami] HD VIP US",
      "NBC10 [Albany] HD VIP US",
      "NBCSN HD VIP US",
      "NBCSN Nonhwest] HD VIP US",
      "NBC11 [Minneapolis] HD VIP US",
      "NBC8 Bay Area] HD VIP US",
      "NBC8 Bay Area Plus] HD VIP US",
      "CW50 [Detroit] HD VIP US",
      "FOX45 [Baltimore] HD VIP US",
      "FOX17 [Des Moines] HD VIP US",
      "CW69 [Atlanta] HD VIP US",
      "CBS12 [Cape Girardeau] HD VIP US",
      "CW44 [St. Petersburg] HD VIP US",
      "CBS19 [Cleveland] HD VIP US",
      "CBS12 [Cincinnati] HD VIP US",
      "CBS3 [Springfield] HD VIP US",
      "CBS4 [Boston] HD VIP US",
      "CBS32 [Louisville] HD VIP US",
      "CBS8 [Des Moines-ames] HD VIP US",
      "CBS4 [Miami] HD VIP US",
      "CBS4 [DC Washington] HD VIP US",
      "CBS11 [Little Rock] HD VIP US",
      "CBS4 [New Orleans] HD VIP US",
      "CBS5 [Bay City] HD VIP US",
      "CBS12 [Shreveport] HD VIP US",
      "CBS21 [Cape Girardea] HD VIP US",
      "CBS9 [Cadillac] HD VIP US",
      "CBS3 [Kalamazoo] HD VIP US",
      "CBS44 [Evansville] HD VIP US CBS11 [Houston] HD VIP US",
      "NBC2 Houston] HD VIP US",
      "FOX46 [Charlotte] HD VIP US",
    ]
  }, {
    name: 'USA Locals',
    channels: [
      "FOX5 [New York] HD VIP US",
      "CBS2 [New York] HD VIP US",
      "NBC4 New York ] HD VIP US",
      "FOX43 [York] HD VIP US",
      "FOX5 Washington] HD VIP US",
      "FOX11 [Los Angeles] HD VIP US",
      "CBS9 [Los Angeles] HD VIP US",
      "CBS12 jest Palm Beach] HD VIP US",
      "NBC4 Los Angeles] HD VIP US",
      "FOX32 [Chicago] HD VIP US",
      "NBC5  Chicago] HD VIP US",
      "FOX25 [Boston] HD VIP US",
      "CBS3 [Philadelphia] HD VIP US",
      "CBS21 [Detroit] HD VIP US",
      "CBS46 [Atlanta] HD VIP US",
      "FOX5 [Atlanta] HD VIP US",
      "CBS11 [Colorado Springs] HD VIP US",
      "NBC11 [Baltimore] HD VIP US",
      "FOX35 [Orlando] HD VIP US",
      "CBS6 [Orlando] HD VIP US",
      "FOX9 [Minneapolis] HD VIP US",
      "CBS3 [Omaha] HD VIP US",
      "NBC6 Omaha] HD VIP US",
      "FOX54 [Columbus] HD VIP US",
      "NBC38 [Columbus] HD VIP US",
      "CBS22 [South Bend] HD VIP US",
      "FOX11 [San Luis Obispo] HD VIP US",
      "CBS13 [Baltimore] HD VIP US",
      "NBC11 [Fairbanks] HD VIP US",
      "NBC5 Juneau-douglas] HD VIP US",
      "NBC21 [Austin] HD VIP US",
      "CBS4 [St. Louis] HD VIP US",
      "FOX54 [Huntsville] HD VIP US",
      "CBS4 [Kansas City] HD VIP US",
      "NBC15 [Mobile] HD VIP US",
      "NBC12 [Montgomery] HD VIP US",
      "FOX16 [Little Rock] HD VIP US",
      "NBC12 [Mesa] HD VIP US",
      "CBS5 [Phoenix] HD VIP US",
      "FOX10 [Phoenix] HD VIP US",
      "FOX11 |Tucson] HD VIP US",
      "CBS29 [Bakersfield] HD VIP US",
      "NBC17 [Bakersfield] HD VIP US",
      "NBC24 [Chico] HD VIP US",
      "NBC24 [Fresno] HD VIP US",
      "CBS46 [Monterey] HD VIP US",
      "FOX2 [Oakland] HD VIP US",
      "FOX40 [Sacramento] HD VIP US",
      "NBC3 Sacramento] HD VIP US",
      "NBC8 Salinas] HD VIP US",
      "FOX5 [San Diego] HD VIP US",
      "CBS13 [Portland] HD VIP US",
      "FOX51 [Ocala] HD VIP US",
      "NBC7 Panama City] HD VIP US",
      "NBC40 |TaIIahassee] HD VIP US",
      "FOX13 |Tampa] HD VIP US",
      "FOX29 [West Palm Beach] HD VIP US",
      "NBC5 West Palm Beach] HD VIP US",
      "CBS12 [Augusta] HD VIP US",
      "FOX54 [Augusta] HD VIP US",
      "NBC41 [Macon] HD VIP US",
      "CBS6 |ThomasviIIe] HD VIP US",
      "CBS5 [Honolulu] HD VIP US",
      "NBC35 [Honolulu] HD VIP US",
      "NBC6 Kurtistown] HD VIP US",
      "NBC4 Sioux City] HD VIP US",
      "NBC13 [Des Moines] HD VIP US",
      "CBS2 [Boise] HD VIP US",
      "NBC34 [Binghamton] HD VIP US",
      "NBC2 Buffalo] HD VIP US",
      "NBC11 [Pittsburgh] HD VIP US",
      "FOX43 |Virginia Beach] HD VIP US",
      "CBS3 [Madison] HD VIP US",
      "CBS19 [Nacogdoches] HD VIP US",
      "FOX30 [San Antonio] HD VIP US",
      "NBC4 San Antonio] HD VIP US",
      "NBC6  temple] HD VIP US",
      "CBS10 Waco] HD VIP US",
      "FOX44 [Waco] HD VIP US",
      "FOX13 [Salt Lake City] HD VIP US",
      "NBC10 [Albany] HD VIP US",
      "NBC11 [Minneapolis] HD VIP US",
      "NBC8 Laredo] HD VIP US",
      "CBS12 [Cape Girardeau] HD VIP US",
      "CW44 [St. Petersburg] HD VIP US",
      "CBS19 [Cleveland] HD VIP US",
      "CBS12 [Cincinnati] HD VIP US",
      "CBS3 [Springfield] HD VIP US",
      "CBS4 [Boston] HD VIP US",
      "CBS32 [Louisville] HD VIP US",
      "CBS4 [Miami] HD VIP US",
      "CBS9 [Washington] HD VIP US",
      "CBS11 [Little Rock] HD VIP US",
      "NBC7 Waterloo] HD VIP US",
      "CBS5 [Bay City] HD VIP US",
      "CBS12 [Shreveport] HD VIP US",
      "CBS9 [Cadillac] HD VIP US",
      "CBS3 [Kalamazoo] HD VIP US",
      "CBS11 [Houston] HD VIP US",
      "NBC2 Houston] HD VIP US",
      "FOX46 [Charlotte] HD VIP US",
      "CBS21 [Danville] HD VIP US",
      "NBC28 [Danville] HD VIP US",
      "FOX56 [Danville] HD VIP US",
    ]
  }, {
    name: 'United States channels',
    channels: [
      "USA Sports​",
      "NFL Network FHD VIP US",
      "NFL Network HD VIP US",
      "MLB Network FHD US",
      "MLB Network HD US",
      "NBA TV HD VIP US",
      "NBA TV HD US",
      "NHL Network HD US",
      "NBC Sports Bay Area HD US",
      "NBC Sports Boston FHD US",
      "NBC Sports Philadelphia HD VIP US",
      "NBC Sports California FHD US",
      "NBC Sports Chicago HD VIP US",
      "NBC Sports Chicago Plus VIP US",
      "NBC Sports Washington HD US",
      "NBC Golf FHD US",
      "NBC Golf HD US",
      "NBC Golf US",
      "Golf Channel HD VIP US",
      "Fox Sports 1 HD US",
      "Fox Sports 1 US",
      "Fox Sports 2 HD US",
      "Fox Sports 2 US",
      "Fox Soccer Plus HD US",
      "Bally Sports Ohio HD VIP",
      "Bally Sports San Diego HD VIP US",
      "Bally Sports Midwest HD VIP US",
      "Bally Sports SoCaI HD US",
      "ESPN News HD US",
      "ESPN FHD VIP US",
      "ESPN HD US",
      "ESPN 2 FHD VIP US",
      "ESPN 2 HD US",
      "ESPN U HD US",
      "ESPN U US",
      "ESPN Sec Network HD US",
      "ESPN Deportee HD US",
      "TSN 1 HD US",
      "TSN 2 HD US",
      "TSN 3 HD VIP US",
      "TSN 4 HD VIP US",
      "TSN 5 HD VIP US",
      "Yes Network HD VIP US",
      "SNY HD VIP US",
      "MSG HD US",
      "MSG+ HD VIP US",
      "Pac-12 Network HD VIP US",
      "PAC-12 Oregon HD VIP US",
      "PAC-12 Oregon US",
      "PAC-12 Los Angeles] HD VIP US",
      "Big Ten Network HD VIP US",
      "Big Ten Network HD US",
      "CBS Sports Network HD US",
      "beIN Sports FHD US",
      "beiN Sports HD US",
      "TUDN HD VIP US",
      "UFC Fight Pass FHD VIP US",
      "WWE Network FHD VIP US",
      "WWE Network HD US",
      "WWE Network [B] HD US",
      "MAV TV HD US",
      "NESN HD US",
      "Tennis Channel FHD VIP US",
      "Tennis Channel HD VIP US",
      "Tennis Channel HD US",
      "Willow Cricket HD US",
      "TVG Network HD VIP US",
      "TVG2 Network HD VIP US",
      "USA News​",
      "One America News HD VIP US",
      "News12 [Bronx] FHD VIP US",
      "News12 [Westchester] HD VIP US",
      "Bloomberg FHD US",
      "Bloomberg HD VIP US",
      "CBSN HD VIP US",
      "CBSN US",
      "CNBC FHD VIP US",
      "CNBC HD US",
      "CNBC World HD VIP US",
      "CNN FHD US",
      "CNN HD US",
      "CNN [B] HD US",
      "CNN US",
      "BBC World News HD VIP US",
      "Fox Business FHD VIP US",
      "Fox Business HD VIP US",
      "Fox News HD VIP US",
      "Fox News HD US",
      "Fox News B] HD US",
      "Fox News US",
      "NewsMax HD US",
      "MSNBC FHD VIP US",
      "MSNBC HD US",
      "USA Movies​",
      "HBO FHD VIP US",
      "HBO Family HD VIP US",
      "HBO Signature FHD VIP US",
      "HBO Comedy FHD US",
      "HBO Comedy HD US",
      "HBO Zone HD VIP US",
      "Showtime HD US",
      "Showtime 2 FHD VIP US",
      "Showtime Showcase HD VIP US",
      "Showtime Next FHD VIP US",
      "Showtime Extreme FHD VIP US",
      "Starz jest] FHD VIP US",
      "Starz Edge FHD VIP US",
      "Starz Kids & Family FHD VIP US",
      "Starz Comedy FHD US",
      "Starz Cinema FHD US",
      "Starz Encore FHD VIP US",
      "Starz Encore Family HD VIP US",
      "Epix HD VIP US",
      "Cinemax [East] HD VIP US",
      "Action Max FHD US",
      "5Star Max HD US",
      "TBS FHD VIP US",
      "TBS HD US",
      "AMC HD VIP US",
      "AMC HD US",
      "AMC US",
      "TNT FHD VIP US",
      "TNT HD US",
      "LMN HD VIP US",
      "Paramount Network HD US",
      "Sony Movie Channel HD VIP US",
      "Freeform HD US",
      "Hallmark FHD VIP US",
      "Hallmark HD VIP US",
      "Hallmark Movies & Mysteries FHD VIP US",
      "Hallmark Drama FHD VIP US",
      "FX FHD US",
      "FX HD US",
      "FXX FHD US",
      "FXX HD US",
      "INSP HD VIP US",
      "IFC HD VIP US",
      "TCM HD US",
      "Cozi TV US",
      "Sundance TV FHD US",
      "Sundance TV HD VIP US",
      "USA Entertainment",
      "BBC America HD VIP US",
      "Fox FHD US",
      "ABC HD US",
      "VH1 HD US",
      "VH1 US",
      "VH1 [West] HD VIP US",
      "VH1 [East] HD VIP US",
      "MTV Classic VIP US",
      "Comedy Central HD US",
      "Comedy Central US",
      "Syfy HD US",
      "E! [East] HD VIP US",
      "E! [West] HD VIP US",
      "POP TV HD VIP US",
      "USA Network HD US",
      "Bravo HD VIP US",
      "Bravo HD US",
      "Lifetime HD US",
      "A&E FHD US",
      "A&E HD US",
      "HGTV HD US",
      "HGTV US",
      "HGTV [East] HD VIP US",
      "OutSide TV HD VIP US",
      "OWN HD US",
      "TLC FHD US",
      "TLC HD US",
      "TLC US",
      "TLC [East] HD VIP US",
      "TLC [West] HD VIP US",
      "Fashion TV FHD US",
      "TRU TV HD US",
      "TV Land HD US",
      "Reelz Channel HD US",
      "WE TV FHD US",
      "Fuse HD US",
      "Oxygen HD US",
      "Oxygen [West] HD VIP US",
      "CBS US",
      "BET [West] HD VIP US",
      "BET Her HD VIP US",
      "Bet Her HD US",
      "CW HD US",
      "CMT HD US",
      "GSN HD VIP US",
      "USA Documentary",
      "Discovery Channel FHD VIP US",
      "Discovery Life HD US",
      "Crime & Investigation FHD VIP US",
      "Investigation Discovery HD US",
      "Discovery Science FHD US",
      "Discovery Science HD VIP US",
      "Destination America FHD VIP US",
      "Destination America HD VIP US",
      "History Channel FHD VIP US",
      "History Channel HD VIP US",
      "History Channel HD US",
      "National Geographic FHD US",
      "National Geographic HD US",
      "Nat Geo Wild FHD US",
      "Animal Planet HD VIP US",
      "Animal Planet HD US",
      "Magnolia Network HD US",
      "Food Network [East] HD VIP US",
      "Cooking Channel HD VIP US",
      "Motortrend HD VIP US",
      "Outdoor Channel HD US",
      "Outdoor Channel HD VIP US",
      "Travel Channel FHD VIP US",
      "The Weather Channel HD VIP US",
      "American Heroes HD US",
      "Smithsonian Channel jest] HD VIP US",
      "Viceland HD US",
      "Sportsman HD VIP US",
      "USA Kids​",
      "Canoon Network FHD VIP US",
      "Canoon Network HD US",
      "Disney Channel HD US",
      "Disney Junior HD US",
      "Disney XD FHD US",
      "Nicktoons HD VIP US",
    ]
  }, {
    name: 'United Kingdom channels',
    channels: [
      "UK Sports​",
      "Sky Sports Main Event FHD VIP UK",
      "Sky Sports Main Event HD VIP UK",
      "Sky Sports Premier League FHD VIP UK",
      "Sky Sports Premier League HD VIP UK",
      "Sky Sports Football FHD VIP UK",
      "Sky Sports Football HD VIP UK",
      "Sky Sports Cricket FHD VIP UK",
      "Sky Sports Cricket HD VIP UK",
      "Sky Sports Golf FHD VIP UK",
      "Sky Sports Golf HD VIP UK",
      "Sky Sports Racing FHD VIP UK",
      "Sky Sports Racing HD VIP UK",
      "Sky Sports F1 FHD VIP UK",
      "Sky Sports F1 HD VIP UK",
      "Sky Sports Action FHD VIP UK",
      "Sky Sports Action HD VIP UK",
      "Sky Sports Arena FHD VIP UK",
      "Sky Sports Arena HD VIP UK",
      "Sky Sports News FHD VIP UK",
      "Sky Sports News HD VIP UK",
      "Sky Sports Mix FHD VIP UK",
      "Sky Sports Mix VIP UK",
      "Sky Sports Mix HD VIP UK",
      "Sky Sports Mix HD VIP UK",
      "Sky Sports Box Office FHD [Match Time] UK",
      "BT Sport 1 FHD VIP UK",
      "BT Sport 1 HD VIP UK",
      "BT Sport 2 FHD VIP UK",
      "BT Sport 2 HD VIP UK",
      "BT Sport 3 FHD VIP UK",
      "BT Sport 3 HD VIP UK",
      "BT Sport Extra 1 VIP [Match Time] UK",
      "BT Sport Extra 2 VIP [Match Time] UK",
      "BT Sport Extra 3 VIP [Match Time] UK",
      "BT Sport Extra 4 VIP [Match Time] UK",
      "BT Sport Extra 5 VIP [Match Time] UK",
      "BT Sport ESPN FHD VIP UK",
      "BT Sport ESPN HD VIP UK",
      "Eurosport 1 FHD VIP UK",
      "Eurosport 2 FHD VIP UK",
      "Box Nation HD VIP UK",
      "Box Nation VIP UK",
      "Premier Sports 1 FHD VIP UK",
      "Premier Sports 1 HD VIP UK",
      "Premier Sports 2 FHD VIP UK",
      "Premier Sports 2 HD VIP UK",
      "Free Sports FHD VIP UK",
      "Free Sports [B] FHD VIP UK",
      "LA LIGA FHD VIP UK",
      "LA LIGA HD VIP UK",
      "Racing FHD VIP UK",
      "Racing HD VIP UK",
      "MUTV FHD VIP UK",
      "Liverpool FC VIP UK",
      "Celtic FC TV [Match Time] HD UK",
      "UK BBC National",
      "BBC One FHD VIP UK",
      "BBC One HD VIP UK",
      "BBC Two FHD VIP UK",
      "BBC Two HD VIP UK",
      "BBC Four FHD VIP UK",
      "BBC News FHD VIP UK",
      "BBC Parliament UK",
      "BBC Alba VIP UK",
      "CBBC FHD VIP UK",
      "CBBC HD VIP UK",
      "UK BBC Regional​",
      "BBC One [Nonhern Ireland] HD VIP UK",
      "BBC One [Scotland] FHD VIP UK",
      "BBC One [Scotland] HD VIP UK",
      "BBC One sales] FHD VIP UK",
      "BBC One sales] HD VIP UK",
      "UK BBC Local​",
      "BBC One [London] VIP UK",
      "BBC One [Nonh West] VIP UK",
      "UK News​",
      "AI Jazeera News FHD UK",
      "BBC News HD VIP UK",
      "BBC World News HD UK",
      "CNN FHD VIP UK",
      "CNN HD VIP UK",
      "Fox News HD UK",
      "France 24 English VIP UK",
      "Sky News FHD VIP UK",
      "Sky News HD VIP UK",
      "RTE News HD VIP UK",
      "UK Movies & Series sa",
      "Sky Cinema Premiere FHD VIP UK",
      "Sky Cinema Premiere HD VIP UK",
      "Sky Cinema Select FHD VIP UK",
      "Sky Cinema Select HD VIP UK",
      "Sky Cinema Hits FHD VIP UK",
      "Sky Cinema Hits HD VIP UK",
      "Sky Cinema Greats FHD VIP UK",
      "Sky Cinema Greats HD VIP UK",
      "Sky Cinema Animation FHD VIP UK",
      "Sky Cinema Family FHD VIP UK",
      "Sky Cinema Family HD VIP UK",
      "Sky Cinema Action FHD VIP UK",
      "Sky Cinema Action HD VIP UK",
      "Sky Cinema Comedy FHD VIP UK",
      "Sky Cinema Comedy HD VIP UK",
      "Sky Cinema Thriller FHD VIP UK",
      "Sky Cinema Thriller HD VIP UK",
      "Sky Cinema Drama FHD VIP UK",
      "Sky Cinema Drama HD VIP UK",
      "Sky Cinema Sci-Fi & Horror FHD VIP UK",
      "Sky Cinema Sci-Fi & Horror HD VIP UK",
      "Sky Witness FHD VIP UK",
      "Film 4 FHD VIP UK",
      "Film 4 HD VIP UK",
      "Paramount FHD VIP UK",
      "TCM FHD VIP UK",
      "TCM HD VIP UK",
      "Talking Pictures TV UK",
      "UK Documentary ‹as Animal Planet FHD VIP UK",
      "Animal Planet HD VIP UK",
      "Crime & Investigation FHD VIP UK",
      "Discovery Channel FHD VIP UK",
      "Discovery History VIP UK",
      "Investigation Discovery VIP UK",
      "Discovery Science VIP UK",
      "Discovery Turbo VIP UK",
      "Sky History FHD VIP UK",
      "Sky History HD VIP UK",
      "Sky History2 FHD VIP UK",
      "Horse & Country UK",
      "National Geographic FHD VIP UK",
      "National Geographic Wild FHD VIP UK",
      "National Geographic Wild HD VIP UK",
      "Sky Documentaries FHD UK",
      "Love Nature HD VIP UK",
      "SKY Nature FHD VIP UK",
      "TV Warehouse UK",
      "UK Entertainment",
      "Sky Showcase FHD VIP UK",
      "Sky Showcase HD VIP UK",
      "Sky Comedy HD UK",
      "Sky Arts FHD VIP UK",
      "Sky Arts HD VIP UK",
      "Sky Atlantic FHD VIP UK",
      "Sky Atlantic HD VIP UK",
      "Sky Replay FHD VIP UK",
      "Sky Max HD VIP UK",
      "Virgin Media One FHD VIP UK",
      "Virgin Media One HD VIP UK",
      "Virgin Media Two FHD VIP UK",
      "Virgin Media Two HD VIP UK",
      "Virgin Media Three FHD VIP UK",
      "Virgin Media Three HD VIP UK",
      "RTE One FHD VIP UK",
      "RTE One HD VIP UK",
      "RTE Two FHD VIP UK",
      "RTE Two HD VIP UK",
      "ITV 1 FHD VIP UK",
      "ITV 1 HD VIP UK",
      "ITV 2 FHD VIP UK",
      "ITV 2 HD VIP UK",
      "ITV 3 FHD VIP UK",
      "ITV 3 HD VIP UK",
      "ITV 4 FHD VIP UK",
      "ITV 4 HD VIP UK",
      "ITV Be HD VIP UK",
      "Blaze VIP UK",
      "CBS Drama VIP UK",
      "CBS Justice VIP UK",
      "Challenge VIP UK",
      "Channel 4 FHD VIP UK",
      "Channel 4 HD VIP UK",
      "Channel 5 FHD VIP UK",
      "Channel 5 HD VIP UK",
      "Channel S Star VIP UK",
      "Comedy Central FHD VIP UK",
      "Comedy Central HD VIP UK",
      "Comedy Central Extra VIP UK",
      "Eden FHD VIP UK",
      "Dave FHD VIP UK",
      "Dave HD VIP UK",
      "Dave ja vu UK",
      "Drama VIP UK",
      "Dmax VIP UK",
      "E! FHD VIP UK",
      "E4 FHD VIP UK",
      "E4 HD VIP UK",
      "Food Network FHD VIP UK",
      "Gold FHD VIP UK",
      "Gold HD VIP UK",
      "Horror Channel VIP UK",
      "London Live UK",
      "More4 FHD VIP UK",
      "PBS America UK",
      "Pick TV VIP UK",
      "Quest FHD VIP UK",
      "Quest Red UK",
      "Rok TV UK",
      "S4C UK",
      "STV FHD VIP UK",
      "STV HD VIP UK",
      "Syfy FHD VIP UK",
      "Syfy HD VIP UK",
      "TG4 HD VIP UK",
      "TLC FHD VIP UK",
      "TLC HD VIP UK",
      "UTV HD VIP UK",
      "Watch FHD VIP UK",
      "Yesterday VIP UK",
      "4Seven FHD VIP UK",
      "5 Star HD VIP UK",
      "Alibi FHD VIP UK",
      "Alibi HD VIP UK",
      "Colors TV VIP UK",
      "Colors Rishtey VIP UK",
      "Sony TV FHD VIP UK",
      "Sony TV UK",
      "Sony Max FHD VIP UK",
      "Sony Max 2 FHD VIP UK",
      "Sony SAB FHD VIP UK",
      "Utv SAT Gold HD VIP UK",
      "Utv SAT Plus HD VIP UK",
      "UK Family",
      "Baby TV VIP UK",
      "Boomerang FHD VIP UK",
      "Boomerang HD VIP UK",
      "Canoon Network FHD VIP UK",
      "Canoon Network HD VIP UK",
      "Canoonito VIP UK",
      "Nick Jr HD UK",
      "Nick Jr TOO HD VIP UK",
      "Nickelodeon FHD VIP UK",
      "Nicktoons HD VIP UK",
      "RTE Jr UK",
      "POP VIP UK",
      "POP MAX VIP UK",
      "Tiny Pop VIP UK",
      "UK Music",
      "4Music VIP UK",
      "MTV FHD VIP UK",
      "MTV Music UK",
      "MTV Hits VIP UK",
      "MTV Base HD VIP UK",
      "MTV 80s VIP UK",
      "MTV 90s VIP UK",
      "Clubland TV VIP UK",
      "Kerrang TV UK",
      "Kiss UK",
      "Magic VIP UK",
      "The Box UK",
      "Box Hits UK",
    ]
  }
]