export const images = {
  starLogo: require('../assets/images/star4.png'),
  family: require('../assets/images/family.png'),
  mainImage: require('../assets/images/mainImage.jpg'),
  manAndChild: require('../assets/images/manAndChild.webp'),
  mobileDevices: require('../assets/images/mobileDevices.webp'),
  movies: require('../assets/images/movies.webp'),
  production: require('../assets/images/production.png'),
  addIcon: require('../assets/images/addIcon.png'),
  bulletIcon: require('../assets/images/bulletIcon.png'),
  checkIcon: require('../assets/images/checkIcon.png'),
  emailIcon: require('../assets/images/emailIcon.png'),
  linkIcon: require('../assets/images/linkIcon.png'),
  playIcon: require('../assets/images/playIcon.png'),
  roundedPlayIcon: require('../assets/images/roundedPlayIcon.png'),
  progressIcon: require('../assets/images/progressIcon.png'),
  tubeIcon: require('../assets/images/tubeIcon.png'),
  tvIcon: require('../assets/images/tvIcon.png'),
  privacyIcon: require('../assets/images/privacyIcon.png'),
  menu: require('../assets/images/menu.png'),
  minusIcon: require('../assets/images/minusIcon.png'),
};
